ERROR:root:An unexpected error occurred
Traceback (most recent call last):
  File "d:\medidor_de_palavras\main.py", line 27, in app_launcher
    show_word_frequency(text, lang)
TypeError: show_word_frequency() takes 1 positional argument but 2 were given
ERROR:root:An unexpected error occurred
Traceback (most recent call last):
  File "d:\medidor_de_palavras\main.py", line 30, in app_launcher
    if not ask_continue():
           ^^^^^^^^^^^^^^
TypeError: ask_continue() missing 1 required positional argument: 'lang'
